### PR TITLE
Update utils.psm1

### PR DESCRIPTION
**Pull request by weekendclimber**
Added lines 10-14 for compatibility with VS2022.
Added version '17.0' to $versions for compatibility with VS2022.
Fixed duplication issue on line 22. (this may not be necessary)

Tested on local build machine with Windows 11 (10.0.22621 Build 22621) and Visual Studio 2022 17.8.2

### CODE REVIEW

**Comment by mmajcica** [comment]
Looks ok, but it is missing something.
In the https://github.com/mmajcica/DevEnvBuild/blob/master/task/task.json
please add in line 63 the new option e.g.
```
      "options": {
        "latest": "Latest",
        "17.0": "Visual Studio 2022",
        "16.0": "Visual Studio 2019",
        "15.0": "Visual Studio 2017",
        "14.0": "Visual Studio 2015",
        "12.0": "Visual Studio 2013",
        "11.0": "Visual Studio 2012"
      }
```

**Comment by mmajcica** [comment]
Also I do not see that you have updated Get-VSSetupInstance
Make sure we are using the latest, https://github.com/microsoft/vssetup.powershell/releases/tag/2.2.16

**Comment by mmajcica** [comment]
In case https://github.com/microsoft/vssetup.powershell/releases/tag/2.2.16 does not support older versions of VS (like 2017 below), we can remove those from the options.

**Comment by weekendclimber** [comment]
Hey @mmajcica,

I've made your requested changes to task.json and update the version of the VSSetup module. Please let me know if there are any others you would like to have added.

**Comment by mmajcica** [comment]
I have just published https://github.com/mmajcica/DevEnvBuild/releases/tag/v2.0.4
Is there anyway for you to test it before I publish it on marketplace?

**Comment by mmajcica** [comment]
@weekendclimber I have now deployed a new version of the extension. 2.0.5. It contains the task with a new major version, 3.0. Are you able to test it? Thanks

**Comment by weekendclimber** [comment]
Unfortunately not working for me. It seems it is adding a path to the 'project' variable on the call to 'Get-VstsInput' in 'task.ps1'. This then throws an error that the call to DEVENV.COM is not valid. This is being run on a local agent against a 'Visual Studio Installer Projects 2022' project (VDPROJ project file extension) that builds a MSI file.

The call ends up as this:

```
"C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.com" "C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13.sln" /Project "C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13 Setup" /Rebuild "Release|x86"
```

The "/Project", I believe, should only have the name of the project. In my case this call works:

```
"C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.com" "C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13.sln" /Project "Employee Labor Recon v2.13 Setup" /Rebuild "Release|x86"
```

The project name is all I'm giving it in my pipeline yaml file here:

```
- task: DevEnvBuild@3
  inputs:
    solution: 'Employee Labor Recon v2.13.sln'
    project: 'Employee Labor Recon v2.13 Setup'
    buildCfg: 'Release'
    buildPlatform: 'x86'
    vsVersion: 'latest'
    clean: true
```

Debug Log:
```2023-12-07T16:47:06.5722251Z ##[debug]Evaluating condition for step: 'DevEnvBuild'
2023-12-07T16:47:06.5722776Z ##[debug]Evaluating: SucceededNode()
2023-12-07T16:47:06.5722870Z ##[debug]Evaluating SucceededNode:
2023-12-07T16:47:06.5723077Z ##[debug]=> True
2023-12-07T16:47:06.5723214Z ##[debug]Result: True
2023-12-07T16:47:06.5723359Z ##[section]Starting: DevEnvBuild
2023-12-07T16:47:06.5845344Z ==============================================================================
2023-12-07T16:47:06.5845418Z Task         : DevEnv build (Visual Studio)
2023-12-07T16:47:06.5845456Z Description  : Build a project via the visual studio command-line invocation, devenv.cmd. Used for building eg. SSIS projects.
2023-12-07T16:47:06.5845526Z Version      : 3.0.0
2023-12-07T16:47:06.5845553Z Author       : Mario Majcica
2023-12-07T16:47:06.5845594Z Help         : Build your project via the visual studio command-line invocation, devenv.cmd
2023-12-07T16:47:06.5845641Z ==============================================================================
2023-12-07T16:47:06.8973297Z . : The term 'C:\Users\user.AD\source\tools\agents\_work\_tasks\DevEnvBuild_ea543240-b4a8-11e5-8761-bb4cd4a06
2023-12-07T16:47:06.8973577Z cfc\3.0.0\ps_modules\VstsTaskSdk\FindFunctions.ps1' is not recognized as the name of a cmdlet, function, script file, 
2023-12-07T16:47:06.8973880Z or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
2023-12-07T16:47:06.8973969Z try again.
2023-12-07T16:47:06.8974751Z At C:\Users\user.AD\source\tools\agents\_work\_tasks\DevEnvBuild_ea543240-b4a8-11e5-8761-bb4cd4a06cfc\3.0.0\p
2023-12-07T16:47:06.8975549Z s_modules\VstsTaskSdk\VstsTaskSdk.psm1:23 char:3
2023-12-07T16:47:06.8976266Z + . "$PSScriptRoot\FindFunctions.ps1"
2023-12-07T16:47:06.8976401Z +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-12-07T16:47:06.8976693Z     + CategoryInfo          : ObjectNotFound: (C:\Users\....ndFunctions.ps1:String) [], CommandNotFoundException
2023-12-07T16:47:06.8976997Z     + FullyQualifiedErrorId : CommandNotFoundException
2023-12-07T16:47:06.8977085Z  
2023-12-07T16:47:07.1404772Z ##[debug]VstsTaskSdk 0.17.0 commit b31a83bf175a3768b346a9def8d95d60f238f089
2023-12-07T16:47:07.2370279Z ##[debug]Entering C:\Users\user.AD\source\tools\agents\_work\_tasks\DevEnvBuild_ea543240-b4a8-11e5-8761-bb4cd4a06cfc\3.0.0\task.ps1.
2023-12-07T16:47:07.2554451Z ##[debug]INPUT_SOLUTION: 'C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13.sln'
2023-12-07T16:47:07.2578903Z ##[debug]INPUT_PROJECT: 'C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13 Setup'
2023-12-07T16:47:07.2600994Z ##[debug]INPUT_BUILDPLATFORM: 'x86'
2023-12-07T16:47:07.2621282Z ##[debug]INPUT_BUILDCFG: 'Release'
2023-12-07T16:47:07.2640319Z ##[debug]INPUT_VSVERSION: 'latest'
2023-12-07T16:47:07.2660334Z ##[debug]INPUT_DEPLOY: 'false'
2023-12-07T16:47:07.2687634Z ##[debug] Converted to bool: False
2023-12-07T16:47:07.2707608Z ##[debug]INPUT_CLEAN: 'true'
2023-12-07T16:47:07.2725250Z ##[debug] Converted to bool: True
2023-12-07T16:47:07.2744133Z ##[debug]Loading module from path 'C:\Users\user.AD\source\tools\agents\_work\_tasks\DevEnvBuild_ea543240-b4a8-11e5-8761-bb4cd4a06cfc\3.0.0\ps_modules\utils.psm1'.
2023-12-07T16:47:07.2820383Z ##[debug]Exporting function 'Get-VSPath'.
2023-12-07T16:47:07.2833743Z ##[debug]Exporting function 'Select-VSVersion'.
2023-12-07T16:47:07.2847288Z ##[debug]Exporting function 'Get-SingleFile'.
2023-12-07T16:47:07.2863094Z ##[debug]Importing function 'Get-SingleFile'.
2023-12-07T16:47:07.2878361Z ##[debug]Importing function 'Get-VSPath'.
2023-12-07T16:47:07.2894442Z ##[debug]Importing function 'Select-VSVersion'.
2023-12-07T16:47:07.2935840Z ##[debug]Finding files with pattern C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13.sln
2023-12-07T16:47:07.3016053Z ##[debug]Entering Find-VstsFiles.
2023-12-07T16:47:07.3078599Z ##[debug] LegacyPattern: 'C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13.sln'
2023-12-07T16:47:07.3285366Z ##[debug]Entering Get-MatchingItems.
2023-12-07T16:47:07.3308777Z ##[debug] IncludePatterns: 'C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13.sln'
2023-12-07T16:47:07.3342679Z ##[debug] ExcludePatterns: ''
2023-12-07T16:47:07.3368235Z ##[debug] IncludeFiles: 'True'
2023-12-07T16:47:07.3385060Z ##[debug] IncludeDirectories: 'False'
2023-12-07T16:47:07.3399619Z ##[debug] Force: 'False'
2023-12-07T16:47:07.5554202Z ##[debug]Path: C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13.sln
2023-12-07T16:47:07.5606255Z ##[debug]Leaving Get-MatchingItems.
2023-12-07T16:47:07.5622034Z ##[debug]Total found: 1
2023-12-07T16:47:07.5636150Z ##[debug]Leaving Find-VstsFiles.
2023-12-07T16:47:07.5650378Z ##[debug]Matched files = C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13.sln
2023-12-07T16:47:07.5668718Z Project is set to 1: C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13 Setup
2023-12-07T16:47:07.5750205Z ##[debug]Entering Select-VSVersion.
2023-12-07T16:47:07.5778310Z ##[debug] PreferredVersion: 'latest'
2023-12-07T16:47:07.5851993Z ##[debug]Loading module from path 'C:\Users\user.AD\source\tools\agents\_work\_tasks\DevEnvBuild_ea543240-b4a8-11e5-8761-bb4cd4a06cfc\3.0.0\ps_modules\VSSetup\Microsoft.VisualStudio.Setup.PowerShell.dll'.
2023-12-07T16:47:07.5976969Z ##[debug]Importing cmdlet 'Get-VSSetupInstance'.
2023-12-07T16:47:07.6011007Z ##[debug]Importing cmdlet 'Select-VSSetupInstance'.
2023-12-07T16:47:07.6026951Z ##[debug]Entering Get-VSPath.
2023-12-07T16:47:07.6040547Z ##[debug] Version: '17.0'
2023-12-07T16:47:07.6473248Z ##[debug]Leaving Get-VSPath.
2023-12-07T16:47:07.6497578Z ##[debug]Leaving Select-VSVersion.
2023-12-07T16:47:07.6512646Z ##[debug]Importing cmdlet 'Get-VSSetupInstance'.
2023-12-07T16:47:07.6524423Z ##[debug]Importing cmdlet 'Select-VSSetupInstance'.
2023-12-07T16:47:07.6537608Z ##[debug]Entering Get-VSPath.
2023-12-07T16:47:07.6551768Z ##[debug] Version: '17.0'
2023-12-07T16:47:07.6722220Z ##[debug]Leaving Get-VSPath.
2023-12-07T16:47:07.6736928Z ##[debug]Resolved Visual Studio path is: C:\Program Files\Microsoft Visual Studio\2022\Professional
2023-12-07T16:47:07.6749691Z Project is set to 2: C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13 Setup
2023-12-07T16:47:07.6750981Z Arguments: "C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13.sln" /Project "C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13 Setup" /Rebuild
2023-12-07T16:47:07.6822245Z ##[debug]Entering Invoke-VstsTool.
2023-12-07T16:47:07.6833877Z ##[debug] FileName: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.com'
2023-12-07T16:47:07.6845891Z ##[debug] Arguments: '"C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13.sln" /Project "C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13 Setup" /Rebuild "Release|x86"'
2023-12-07T16:47:07.6858202Z ##[debug] RequireExitCodeZero: 'True'
2023-12-07T16:47:07.6875012Z ##[command]"C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.com" "C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13.sln" /Project "C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13 Setup" /Rebuild "Release|x86"
2023-12-07T16:47:16.2609025Z 
2023-12-07T16:47:16.2609344Z Microsoft Visual Studio 2022 Version 17.8.3.
2023-12-07T16:47:16.2609421Z Copyright (C) Microsoft Corp. All rights reserved.
2023-12-07T16:47:16.2609728Z Deserializing the project state for project 'ELRv2_13_Production.sqlproj'...
2023-12-07T16:47:17.9146171Z Detecting file changes for project 'ELRv2_13_Production.sqlproj'...
2023-12-07T16:47:17.9159930Z Deserialization has been completed for project 'ELRv2_13_Production.sqlproj'.
2023-12-07T16:47:18.7393946Z 
2023-12-07T16:47:18.7394677Z The operation could not be completed. The parameter is incorrect. 
2023-12-07T16:47:18.7408046Z 
2023-12-07T16:47:18.7408376Z Use:
2023-12-07T16:47:18.7408660Z devenv  [solutionfile | projectfile | folder | anyfile.ext]  [switches]
2023-12-07T16:47:18.7408815Z 
2023-12-07T16:47:18.7409025Z The first argument for devenv is usually a solution file, project file or a folder.
2023-12-07T16:47:18.7412345Z You can also use any other file as the first argument if you want to have the
2023-12-07T16:47:18.7412524Z file open automatically in an editor. When you enter a project file, the IDE
2023-12-07T16:47:18.7416049Z looks for an .sln file with the same base name as the project file in the
2023-12-07T16:47:18.7420399Z parent directory for the project file. If no such .sln file exists, then the
2023-12-07T16:47:18.7420688Z IDE looks for a single .sln file that references the project. If no such single
2023-12-07T16:47:18.7424733Z .sln file exists, then the IDE creates an unsaved solution with a default .sln
2023-12-07T16:47:18.7425170Z file name that has the same base name as the project file.
2023-12-07T16:47:18.7425315Z 
2023-12-07T16:47:18.7425520Z Command line builds:
2023-12-07T16:47:18.7428522Z devenv solutionfile.sln /build [ solutionconfig ] [ /project projectnameorfile [ /projectconfig name ] ]
2023-12-07T16:47:18.7428772Z Available command line switches:
2023-12-07T16:47:18.7428888Z 
2023-12-07T16:47:18.7433644Z /Build			Builds the solution or project with the specified solution
2023-12-07T16:47:18.7433866Z 			configuration. For example "Debug". If multiple platforms
2023-12-07T16:47:18.7434047Z 			are possible, the configuration name must be enclosed in quotes
2023-12-07T16:47:18.7434206Z 			and contain platform name. For example: "Debug|Win32".
2023-12-07T16:47:18.7437684Z /Clean			Deletes build outputs.
2023-12-07T16:47:18.7446243Z /Command		Starts the IDE and executes the command.
2023-12-07T16:47:18.7450068Z /Deploy			Builds and then deploys the specified build configuration.
2023-12-07T16:47:18.7454360Z /DoNotLoadProjects	Opens the specified solution without loading any projects.
2023-12-07T16:47:18.7459396Z /Edit			Opens the specified files in a running instance of this
2023-12-07T16:47:18.7459799Z 			application. If there are no running instances, it will
2023-12-07T16:47:18.7460901Z 			start a new instance with a simplified window layout.
2023-12-07T16:47:18.7466268Z /LCID			Sets the default language in the IDE for the UI.
2023-12-07T16:47:18.7473446Z /Log			Logs IDE activity to the specified file for troubleshooting.
2023-12-07T16:47:18.7474928Z /NoVSIP			Disables the VSIP developer's license key for VSIP testing.
2023-12-07T16:47:18.7478289Z /Out			Appends the build log to a specified file.
2023-12-07T16:47:18.7483227Z /Project		Specifies the project to build, clean, or deploy.
2023-12-07T16:47:18.7483555Z 			Must be used with /Build, /Rebuild, /Clean, or /Deploy.
2023-12-07T16:47:18.7487498Z /ProjectConfig		Overrides the project configuration specified in the solution
2023-12-07T16:47:18.7487928Z 			configuration. For example "Debug". If multiple platforms are
2023-12-07T16:47:18.7488201Z 			possible, the configuration name must be enclosed in quotes
2023-12-07T16:47:18.7488445Z 			and contain platform name. For example: "Debug|Win32".
2023-12-07T16:47:18.7488694Z 			Must be used with /Project.
2023-12-07T16:47:18.7492315Z /Rebuild		Cleans and then builds the solution or project with the
2023-12-07T16:47:18.7495080Z 			specified configuration.
2023-12-07T16:47:18.7500463Z /ResetSettings		Restores the IDE's default settings, optionally resets to
2023-12-07T16:47:18.7500775Z 			the specified VSSettings file.
2023-12-07T16:47:18.7504587Z /ResetSkipPkgs		Clears all SkipLoading tags added to VSPackages.
2023-12-07T16:47:18.7509061Z /Run			Compiles and runs the specified solution.
2023-12-07T16:47:18.7514435Z /RunExit		Compiles and runs the specified solution then closes the IDE.
2023-12-07T16:47:18.7519072Z /SafeMode		Launches the IDE in safe mode loading minimal windows.
2023-12-07T16:47:18.7524045Z /Upgrade		Upgrades the project or the solution and all projects in it.
2023-12-07T16:47:18.7524240Z 			A backup of these files will be created as appropriate. Please
2023-12-07T16:47:18.7524620Z 			see Help on 'Visual Studio Conversion Wizard' for more
2023-12-07T16:47:18.7524814Z 			information on the backup process.```

**Comment by mmajcica** [comment]
What has been invoked is the following (from what I read from the logs)
C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.com" "C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13.sln" /Project "C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13 Setup" /Rebuild "Release|x86"

That looks like a legit invocation.

Also later I do see that project have been found and the processing has started. Then the error The operation could not be completed. The parameter is incorrect. 

Are you able to use the same command locally on you machine to see what is going on?!?!
Are you able to run it locally from command prompt? IF so, what are the params you do pass to devenv?

**Comment by weekendclimber** [comment]
> What has been invoked is the following (from what I read from the logs)
> C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.com" "C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13.sln" /Project "C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13 Setup" /Rebuild "Release|x86"
> 
> That looks like a legit invocation.
> 
> Also later I do see that project have been found and the processing has started. Then the error The operation could not be completed. The parameter is incorrect. 
> 
> Are you able to use the same command locally on you machine to see what is going on?!?!
> Are you able to run it locally from command prompt? IF so, what are the params you do pass to devenv?

From a command line, this is the call that works for me. It is only using the name of the project in the solution that needs to be built. One caveat that I would mention is that this particular project is a Visual Studio Installer Project (VDPROJ).

```
"C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.com" "C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13.sln" /Project "Employee Labor Recon v2.13 Setup" /Rebuild "Release|x86"
```

**Comment by mmajcica** [comment]
Than I have no clue why it would not work on the agent, being invoked from the task. Does agent machine have all of the necessary to build that project? This task does not do much, just invoking devenv, with params. Those we do see in logs are those being executed. If it is not building, it means that something on that agent for that solution is not right.

**Comment by weekendclimber** [comment]
> Than I have no clue why it would not work on the agent, being invoked from the task. Does agent machine have all of the necessary to build that project? This task does not do much, just invoking devenv, with params. Those we do see in logs are those being executed. If it is not building, it means that something on that agent for that solution is not right.

I am able to build the project on the agent with the appropriate parameters, for instance this command works:

```"C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.com" "C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13.sln" /Project "Employee Labor Recon v2.13 Setup" /Rebuild "Release|x86"```

But what is being called in DevEnvBuild is this:

```"C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.com" "C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13.sln" /Project "C:\Users\user.AD\source\tools\agents\_work\1\s\Employee Labor Recon v2.13 Setup" /Rebuild "Release|x86"```

As you can see it seems to be adding a path to the 'project' parameter, which as far as I can tell gets handle with the '$project' parameter in 'task.ps1' ([see my yaml being used in above post](https://github.com/mmajcica/DevEnvBuild/pull/33#issuecomment-1845703742)). I added a couple of lines to output that value, but it is returning from 'Get-VstsInput' with a path included. That's as far as I got. You can see in my original debug output that it is pulled in with that added.

Modified 'task.ps1' file with extra debug output:
```[CmdletBinding()]
param()

Trace-VstsEnteringInvocation $MyInvocation

try {
    [string]$solution = Get-VstsInput -Name solution -Require
    [string]$project = Get-VstsInput -Name project
    [string]$buildPlatform = Get-VstsInput -Name buildPlatform
    [string]$buildCfg = Get-VstsInput -Name buildCfg
    [string]$vsVersion = Get-VstsInput -Name vsVersion
    [bool]$deploy = Get-VstsInput -Name deploy -AsBool
    [bool]$clean = Get-VstsInput -Name clean -AsBool

    Import-Module -Name $PSScriptRoot\ps_modules\utils.psm1

    $solution = Get-SingleFile -pattern $solution

    ##ADDED THIS LINE FOR DEBUGGING OUTPUT
    ##SEE PREVIOUS DEBUG OUTPUT FOR RETURNED VALUE
    Write-Output "Project is set to 1: $project"

    if ($project -eq $env:BUILD_SOURCESDIRECTORY) {
        # In case param is not supplied, AzDO will initialize all fields
        # of type filePath to BUILD_SOURCESDIRECTORY value.
        # As the script logic assumes this to be empty, I reset the value
		$project = ""
    }

    # if project path doesn't exist or it's not valid
    if ($project -and -not (Test-Path $project -PathType Leaf -IsValid)) {
        throw "Provided project file path is not a valid or it can't be found."
    }
		
    # Resolve a VS version.
    $vsVersion = Select-VSVersion -PreferredVersion $vsVersion

    # If no VS found, throw exception
    if (!$vsVersion) {
        throw "Visual Studio was not found. Try installing a supported version of Visual Studio. See the task definition for a list of supported versions."
    }

    $vsLocation = Get-VSPath -Version $vsVersion
    Write-Verbose "Resolved Visual Studio path is: $vsLocation"
    $devcmd = Join-Path $vsLocation "Common7\IDE\devenv.com"

    # if project path doesn't exist or it's not valid
    if (-not (Test-Path $devcmd -PathType Leaf -IsValid)) {
        throw "Expected devenv.com path is not valid."
    }

    ##ADDED THIS LINE FOR DEBUGGING OUTPUT
    ##SEE PREVIOUS DEBUG OUTPUT FOR RETURNED VALUE
    Write-Output "Project is set to 2: $project"

    # Construct invocation arguments
    $vsArgs = """$solution"""

    if ($project) {
        $vsArgs += " /Project ""$project"""
    }

    if ($deploy) {
        $vsArgs += " /Deploy"
    }
    else {
        if ($clean) {
            $vsArgs += " /Rebuild"
        }
        else {
            $vsArgs += " /Build"
        }
    }

	Write-Output "Arguments: $vsArgs"

    if ($buildCfg) { 
        $solutionConfig = " $buildCfg"
        if ($buildPlatform) {
            $solutionConfig = (' "{0}|{1}"' -f $buildCfg, $buildPlatform)
        }

        $vsArgs += $solutionConfig
    }

    Invoke-VstsTool -FileName $devcmd -Arguments $vsArgs -RequireExitCodeZero

    Write-Output "Build succeeded."
}
finally {
    Trace-VstsLeavingInvocation $MyInvocation
}```

**Pull request closed without merging**
